version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging into ECR
      - aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin 907221691199.dkr.ecr.ap-southeast-1.amazonaws.com

  build:
    commands:
      - echo build started on `date` 
      - docker build -t docker_deploy .
      - docker tag docker_deploy:latest 907221691199.dkr.ecr.ap-southeast-1.amazonaws.com/docker_deploy:latest

  post_build:
    commands: 
      - echo Pushing docker image
      - docker push 907221691199.dkr.ecr.ap-southeast-1.amazonaws.com/docker_deploy:latest
      